lecture-7-hw
AnnaNosova/react-study pull request #5
Opened 2024-07-29 15:55 UTC by AnnaNosova

2024-07-30 12:36 UTC, zubkov7 requested changes

2024-07-30 12:36 UTC, zubkov7 commented on src/components/restaurants-page/restaurants-page.jsx
> +    const ids = useSelector(selectRestaurantIds);
не факт, что айди и имя будет лежат в одном порядке, поэтому лучше использовать только id и по нему селектить нужный ресторан, либо сделать специальный селектор ids and names

2024-07-30 19:19 UTC, AnnaNosova commented on src/components/restaurants-page/restaurants-page.jsx
> +    const ids = useSelector(selectRestaurantIds);
Да, самой не нравился этот момент. Сделала другой селектор

2024-07-31 10:43 UTC, zubkov7 approved these changes

2024-07-31 12:37 UTC, merged